### ISSUE TITLE
activityId missing in current state response

### ISSUE THREAD

**Issue by mikehaller** [eclipse-leda/leda-contrib-self-update-agent#21]
The activityId is supposed to be a correlation id, so that i can correlate my operation requests with the corresponding responses.

For example, when requesting the current state with an `activityId`, i expect the response to also contain the `activitId`

The current implementaiton is missing the activityId in the response.

**Comment by mikehaller** [comment]
Sorry, my bad, have been using an oudated build. It works in build-38

**Comment by tobiwan3** [comment]
@mikehaller, can you point us to the place where you include this build in Leda? Then we can make a PR to update.
FYI @OleksandrChaika

**Comment by mikehaller** [comment]
We're updating it in our meta-leda repository.
